import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "./data/schema.graphql",
  documents: "./graphql/**/*.graphql",
  config: {
    useTypeImports: true,
    avoidOptionals:{
      field: true,
      inputValue: false,
      object: false
    },
    scalars: {
      UUID: "string",
      Cursor: "string",
      // Username: "string",
      // Url: "string",
      // Tag: "string",
      Datetime: "string",
      BigInt: "string",
      JSON: "{ [key: string]: any }",
    },
        immutableTypes: true,
        enumsAsTypes: true,
        // namingConvention: "change-case#pascalCase",
        // noGraphQLTag: false,
        dedupeFragments: true,
        // skipTypename: true,
  },
  generates: {
    "./app/utils/graphql.ts": {
      plugins: [
        { add: { content: ["/* WARNING: This file is automatically generated. Do not edit. */"] } },
        { add: { content: ["/* eslint-disable import/first */"] } },
        { add: { content: ["/* tslint:disable */"] } },
        // { add: { content: ["/* eslint:disable */"] } },
        // { add: { content: ["// @ts-nocheck"] } },
        "typescript-operations",
        // "typescript-resolvers",
        "typescript-vue-urql",
      ],
    },
    "./app/utils/introspection.ts": {
      plugins: ["urql-introspection"],
    },
  },
};
export default config;
