/* WARNING: This file is automatically generated. Do not edit. */
/* eslint-disable import/first */
/* tslint:disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import gql from 'graphql-tag';
import * as Urql from '@urql/vue';
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
/** Represents an update to a `Organization`. Fields that are set will be updated. */
export type OrganizationPatch = {
  readonly name?: string | null | undefined;
  readonly slug?: string | null | undefined;
};

/** All input for the `updateOrganization` mutation. */
export type UpdateOrganizationInput = {
  /**
   * An arbitrary string value with no semantic meaning. Will be included in the
   * payload verbatim. May be used to track mutations by the client.
   */
  readonly clientMutationId?: string | null | undefined;
  readonly id: string;
  /** An object where the defined keys will be set on the `Organization` being updated. */
  readonly patch: OrganizationPatch;
};

/** Represents an update to a `User`. Fields that are set will be updated. */
export type UserPatch = {
  /** Optional avatar URL. */
  readonly avatarUrl?: string | null | undefined;
  /** Public-facing name (or pseudonym) of the user. */
  readonly name?: string | null | undefined;
  /** Public-facing username (or 'handle') of the user. */
  readonly username?: string | null | undefined;
};

export type AcceptOrganizationInviteMutationVariables = Exact<{
  id: string;
  code?: string | null | undefined;
}>;


export type AcceptOrganizationInviteMutation = { readonly acceptInvitationToOrganization: { readonly clientMutationId: string | null } | null };

export type AddEmailMutationVariables = Exact<{
  email: string;
}>;


export type AddEmailMutation = { readonly createUserEmail: { readonly user: { readonly id: string, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly email: string, readonly isVerified: boolean, readonly isPrimary: boolean, readonly createdAt: string }> } } | null } | null };

export type ChangePasswordMutationVariables = Exact<{
  oldPassword: string;
  newPassword: string;
}>;


export type ChangePasswordMutation = { readonly changePassword: { readonly success: boolean | null } | null };

export type ConfirmAccountDeletionMutationVariables = Exact<{
  token: string;
}>;


export type ConfirmAccountDeletionMutation = { readonly confirmAccountDeletion: { readonly success: boolean | null } | null };

export type CreatedOrganizationFragment = { readonly id: string, readonly name: string, readonly slug: string };

export type CreateOrganizationMutationVariables = Exact<{
  name: string;
  slug: string;
}>;


export type CreateOrganizationMutation = { readonly createOrganization: { readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null, readonly query: { readonly organizationBySlug: { readonly id: string, readonly name: string, readonly slug: string } | null } | null } | null };

export type CurrentUserAuthenticationsQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserAuthenticationsQuery = { readonly currentUser: { readonly id: string, readonly authentications: ReadonlyArray<{ readonly id: string, readonly service: string, readonly identifier: string, readonly createdAt: string }> } | null };

export type CurrentUserUpdatedSubscriptionVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserUpdatedSubscription = { readonly currentUserUpdated: { readonly event: string | null, readonly user: { readonly id: string, readonly username: string, readonly name: string | null, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean } | null } | null };

export type DeleteEmailMutationVariables = Exact<{
  emailId: string;
}>;


export type DeleteEmailMutation = { readonly deleteUserEmail: { readonly user: { readonly id: string, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly email: string, readonly isVerified: boolean, readonly isPrimary: boolean, readonly createdAt: string }> } } | null } | null };

export type DeleteOrganizationMutationVariables = Exact<{
  organizationId: string;
}>;


export type DeleteOrganizationMutation = { readonly deleteOrganization: { readonly clientMutationId: string | null } | null };

export type EmailsForm_UserFragment = { readonly id: string, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly email: string, readonly isVerified: boolean, readonly isPrimary: boolean, readonly createdAt: string }> } };

export type EmailsForm_UserEmailFragment = { readonly id: string, readonly email: string, readonly isVerified: boolean, readonly isPrimary: boolean, readonly createdAt: string };

export type ForgotPasswordMutationVariables = Exact<{
  email: string;
}>;


export type ForgotPasswordMutation = { readonly forgotPassword: { readonly clientMutationId: string | null } | null };

export type InvitationDetailQueryVariables = Exact<{
  id: string;
  code?: string | null | undefined;
}>;


export type InvitationDetailQuery = { readonly organizationForInvitation: { readonly id: string, readonly name: string, readonly slug: string } | null, readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type InviteToOrganizationMutationVariables = Exact<{
  organizationId: string;
  email?: string | null | undefined;
  username?: string | null | undefined;
}>;


export type InviteToOrganizationMutation = { readonly inviteToOrganization: { readonly clientMutationId: string | null } | null };

export type LoginMutationVariables = Exact<{
  username: string;
  password: string;
}>;


export type LoginMutation = { readonly login: { readonly user: { readonly id: string, readonly username: string, readonly name: string | null } } | null };

export type LogoutMutationVariables = Exact<{ [key: string]: never; }>;


export type LogoutMutation = { readonly logout: { readonly success: boolean | null } | null };

export type MakeEmailPrimaryMutationVariables = Exact<{
  emailId: string;
}>;


export type MakeEmailPrimaryMutation = { readonly makeEmailPrimary: { readonly user: { readonly id: string, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isPrimary: boolean }> } } | null } | null };

export type OrganizationBySlugQueryVariables = Exact<{
  slug: string;
}>;


export type OrganizationBySlugQuery = { readonly organizationBySlug: { readonly id: string, readonly name: string, readonly slug: string } | null };

export type OrganizationMembers_MembershipFragment = { readonly id: string, readonly createdAt: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly user: { readonly id: string, readonly username: string, readonly name: string | null } | null };

export type OrganizationMembers_OrganizationFragment = { readonly id: string, readonly name: string, readonly slug: string, readonly currentUserIsOwner: boolean | null, readonly currentUserIsBillingContact: boolean | null, readonly organizationMemberships: { readonly totalCount: number, readonly nodes: ReadonlyArray<{ readonly id: string, readonly createdAt: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly user: { readonly id: string, readonly username: string, readonly name: string | null } | null }> } };

export type OrganizationMembersQueryVariables = Exact<{
  slug: string;
  offset?: number | null | undefined;
}>;


export type OrganizationMembersQuery = { readonly organizationBySlug: { readonly id: string, readonly name: string, readonly slug: string, readonly currentUserIsOwner: boolean | null, readonly currentUserIsBillingContact: boolean | null, readonly organizationMemberships: { readonly totalCount: number, readonly nodes: ReadonlyArray<{ readonly id: string, readonly createdAt: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly user: { readonly id: string, readonly username: string, readonly name: string | null } | null }> } } | null, readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type OrganizationPageQueryVariables = Exact<{
  slug: string;
}>;


export type OrganizationPageQuery = { readonly organizationBySlug: { readonly id: string, readonly name: string, readonly slug: string, readonly currentUserIsOwner: boolean | null, readonly currentUserIsBillingContact: boolean | null } | null, readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type OrganizationPage_OrganizationFragment = { readonly id: string, readonly name: string, readonly slug: string, readonly currentUserIsOwner: boolean | null, readonly currentUserIsBillingContact: boolean | null };

export type OrganizationPage_QueryFragment = { readonly organizationBySlug: { readonly id: string, readonly name: string, readonly slug: string, readonly currentUserIsOwner: boolean | null, readonly currentUserIsBillingContact: boolean | null } | null, readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type ProfileSettingsForm_UserFragment = { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null };

export type RegisterMutationVariables = Exact<{
  username: string;
  password: string;
  email: string;
  name?: string | null | undefined;
}>;


export type RegisterMutation = { readonly register: { readonly user: { readonly id: string, readonly username: string, readonly name: string | null } } | null };

export type RemoveFromOrganizationMutationVariables = Exact<{
  organizationId: string;
  userId: string;
}>;


export type RemoveFromOrganizationMutation = { readonly removeFromOrganization: { readonly clientMutationId: string | null } | null };

export type RequestAccountDeletionMutationVariables = Exact<{ [key: string]: never; }>;


export type RequestAccountDeletionMutation = { readonly requestAccountDeletion: { readonly success: boolean | null } | null };

export type ResendEmailVerificationMutationVariables = Exact<{
  emailId: string;
}>;


export type ResendEmailVerificationMutation = { readonly resendEmailVerificationCode: { readonly success: boolean | null } | null };

export type ResetPasswordMutationVariables = Exact<{
  userId: string;
  token: string;
  password: string;
}>;


export type ResetPasswordMutation = { readonly resetPassword: { readonly success: boolean | null } | null };

export type SettingsEmailsQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsEmailsQuery = { readonly currentUser: { readonly id: string, readonly isVerified: boolean, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly email: string, readonly isVerified: boolean, readonly isPrimary: boolean, readonly createdAt: string }> }, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type SettingsPasswordQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsPasswordQuery = { readonly currentUser: { readonly id: string, readonly hasPassword: boolean | null, readonly userEmails: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly email: string }> } } | null };

export type SettingsProfileQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsProfileQuery = { readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type SharedQueryVariables = Exact<{ [key: string]: never; }>;


export type SharedQuery = { readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type SharedLayout_QueryFragment = { readonly currentUser: { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } } | null };

export type SharedLayout_UserFragment = { readonly id: string, readonly name: string | null, readonly username: string, readonly avatarUrl: string | null, readonly isAdmin: boolean, readonly isVerified: boolean, readonly organizationMemberships: { readonly nodes: ReadonlyArray<{ readonly id: string, readonly isOwner: boolean, readonly isBillingContact: boolean, readonly organization: { readonly id: string, readonly name: string, readonly slug: string } | null }> } };

export type TransferOrganizationBillingContactMutationVariables = Exact<{
  organizationId: string;
  userId: string;
}>;


export type TransferOrganizationBillingContactMutation = { readonly transferOrganizationBillingContact: { readonly organization: { readonly id: string, readonly currentUserIsBillingContact: boolean | null } | null } | null };

export type TransferOrganizationOwnershipMutationVariables = Exact<{
  organizationId: string;
  userId: string;
}>;


export type TransferOrganizationOwnershipMutation = { readonly transferOrganizationOwnership: { readonly organization: { readonly id: string, readonly currentUserIsOwner: boolean | null } | null } | null };

export type UnlinkUserAuthenticationMutationVariables = Exact<{
  id: string;
}>;


export type UnlinkUserAuthenticationMutation = { readonly deleteUserAuthentication: { readonly user: { readonly id: string, readonly userAuthenticationsList: ReadonlyArray<{ readonly id: string, readonly identifier: string, readonly service: string, readonly createdAt: string }> } | null } | null };

export type UpdateOrganizationMutationVariables = Exact<{
  input: UpdateOrganizationInput;
}>;


export type UpdateOrganizationMutation = { readonly updateOrganization: { readonly organization: { readonly id: string, readonly slug: string, readonly name: string } | null } | null };

export type UpdateUserMutationVariables = Exact<{
  id: string;
  patch: UserPatch;
}>;


export type UpdateUserMutation = { readonly updateUser: { readonly clientMutationId: string | null, readonly user: { readonly id: string, readonly name: string | null, readonly username: string } | null } | null };

export type VerifyEmailMutationVariables = Exact<{
  id: string;
  token: string;
}>;


export type VerifyEmailMutation = { readonly verifyEmail: { readonly success: boolean | null, readonly query: { readonly currentUser: { readonly id: string, readonly isVerified: boolean } | null } | null } | null };

export const CreatedOrganizationFragmentDoc = gql`
    fragment CreatedOrganization on Organization {
  id
  name
  slug
}
    `;
export const EmailsForm_UserEmailFragmentDoc = gql`
    fragment EmailsForm_UserEmail on UserEmail {
  id
  email
  isVerified
  isPrimary
  createdAt
}
    `;
export const EmailsForm_UserFragmentDoc = gql`
    fragment EmailsForm_User on User {
  id
  userEmails(first: 50) {
    nodes {
      ...EmailsForm_UserEmail
      id
      email
      isVerified
    }
  }
}
    ${EmailsForm_UserEmailFragmentDoc}`;
export const OrganizationPage_OrganizationFragmentDoc = gql`
    fragment OrganizationPage_Organization on Organization {
  id
  name
  slug
  currentUserIsOwner
  currentUserIsBillingContact
}
    `;
export const OrganizationMembers_MembershipFragmentDoc = gql`
    fragment OrganizationMembers_Membership on OrganizationMembership {
  id
  createdAt
  isOwner
  isBillingContact
  user {
    id
    username
    name
  }
}
    `;
export const OrganizationMembers_OrganizationFragmentDoc = gql`
    fragment OrganizationMembers_Organization on Organization {
  id
  ...OrganizationPage_Organization
  name
  slug
  organizationMemberships(first: 10, offset: $offset, orderBy: [MEMBER_NAME_ASC]) {
    nodes {
      id
      ...OrganizationMembers_Membership
    }
    totalCount
  }
}
    ${OrganizationPage_OrganizationFragmentDoc}
${OrganizationMembers_MembershipFragmentDoc}`;
export const SharedLayout_UserFragmentDoc = gql`
    fragment SharedLayout_User on User {
  id
  name
  username
  avatarUrl
  isAdmin
  isVerified
  organizationMemberships(first: 20) {
    nodes {
      id
      isOwner
      isBillingContact
      organization {
        id
        name
        slug
      }
    }
  }
}
    `;
export const SharedLayout_QueryFragmentDoc = gql`
    fragment SharedLayout_Query on Query {
  currentUser {
    id
    ...SharedLayout_User
  }
}
    ${SharedLayout_UserFragmentDoc}`;
export const OrganizationPage_QueryFragmentDoc = gql`
    fragment OrganizationPage_Query on Query {
  ...SharedLayout_Query
  organizationBySlug(slug: $slug) {
    id
    ...OrganizationPage_Organization
  }
}
    ${SharedLayout_QueryFragmentDoc}
${OrganizationPage_OrganizationFragmentDoc}`;
export const ProfileSettingsForm_UserFragmentDoc = gql`
    fragment ProfileSettingsForm_User on User {
  id
  name
  username
  avatarUrl
}
    `;
export const AcceptOrganizationInviteDocument = gql`
    mutation AcceptOrganizationInvite($id: UUID!, $code: String) {
  acceptInvitationToOrganization(input: {invitationId: $id, code: $code}) {
    clientMutationId
  }
}
    `;

export function useAcceptOrganizationInviteMutation() {
  return Urql.useMutation<AcceptOrganizationInviteMutation, AcceptOrganizationInviteMutationVariables>(AcceptOrganizationInviteDocument);
};
export const AddEmailDocument = gql`
    mutation AddEmail($email: String!) {
  createUserEmail(input: {userEmail: {email: $email}}) {
    user {
      id
      userEmails(first: 50) {
        nodes {
          id
          ...EmailsForm_UserEmail
        }
      }
    }
  }
}
    ${EmailsForm_UserEmailFragmentDoc}`;

export function useAddEmailMutation() {
  return Urql.useMutation<AddEmailMutation, AddEmailMutationVariables>(AddEmailDocument);
};
export const ChangePasswordDocument = gql`
    mutation ChangePassword($oldPassword: String!, $newPassword: String!) {
  changePassword(input: {oldPassword: $oldPassword, newPassword: $newPassword}) {
    success
  }
}
    `;

export function useChangePasswordMutation() {
  return Urql.useMutation<ChangePasswordMutation, ChangePasswordMutationVariables>(ChangePasswordDocument);
};
export const ConfirmAccountDeletionDocument = gql`
    mutation ConfirmAccountDeletion($token: String!) {
  confirmAccountDeletion(input: {token: $token}) {
    success
  }
}
    `;

export function useConfirmAccountDeletionMutation() {
  return Urql.useMutation<ConfirmAccountDeletionMutation, ConfirmAccountDeletionMutationVariables>(ConfirmAccountDeletionDocument);
};
export const CreateOrganizationDocument = gql`
    mutation CreateOrganization($name: String!, $slug: String!) {
  createOrganization(input: {name: $name, slug: $slug}) {
    organization {
      id
      ...CreatedOrganization
    }
    query {
      organizationBySlug(slug: $slug) {
        id
        ...CreatedOrganization
      }
    }
  }
}
    ${CreatedOrganizationFragmentDoc}`;

export function useCreateOrganizationMutation() {
  return Urql.useMutation<CreateOrganizationMutation, CreateOrganizationMutationVariables>(CreateOrganizationDocument);
};
export const CurrentUserAuthenticationsDocument = gql`
    query CurrentUserAuthentications {
  currentUser {
    id
    authentications: userAuthenticationsList(first: 50) {
      id
      service
      identifier
      createdAt
    }
  }
}
    `;

export function useCurrentUserAuthenticationsQuery(options?: Omit<Urql.UseQueryArgs<never, CurrentUserAuthenticationsQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<CurrentUserAuthenticationsQuery, CurrentUserAuthenticationsQueryVariables | undefined>({ query: CurrentUserAuthenticationsDocument, variables: undefined, ...options });
};
export const CurrentUserUpdatedDocument = gql`
    subscription CurrentUserUpdated {
  currentUserUpdated {
    event
    user {
      id
      username
      name
      avatarUrl
      isAdmin
      isVerified
    }
  }
}
    `;

export function useCurrentUserUpdatedSubscription<R = CurrentUserUpdatedSubscription>(options?: Omit<Urql.UseSubscriptionArgs<never, CurrentUserUpdatedSubscriptionVariables | undefined>, 'query'>, handler?: Urql.SubscriptionHandlerArg<CurrentUserUpdatedSubscription, R>) {
  return Urql.useSubscription<CurrentUserUpdatedSubscription, R, CurrentUserUpdatedSubscriptionVariables | undefined>({ query: CurrentUserUpdatedDocument, variables: undefined, ...options }, handler);
};
export const DeleteEmailDocument = gql`
    mutation DeleteEmail($emailId: UUID!) {
  deleteUserEmail(input: {id: $emailId}) {
    user {
      id
      userEmails(first: 50) {
        nodes {
          id
          ...EmailsForm_UserEmail
        }
      }
    }
  }
}
    ${EmailsForm_UserEmailFragmentDoc}`;

export function useDeleteEmailMutation() {
  return Urql.useMutation<DeleteEmailMutation, DeleteEmailMutationVariables>(DeleteEmailDocument);
};
export const DeleteOrganizationDocument = gql`
    mutation DeleteOrganization($organizationId: UUID!) {
  deleteOrganization(input: {organizationId: $organizationId}) {
    clientMutationId
  }
}
    `;

export function useDeleteOrganizationMutation() {
  return Urql.useMutation<DeleteOrganizationMutation, DeleteOrganizationMutationVariables>(DeleteOrganizationDocument);
};
export const ForgotPasswordDocument = gql`
    mutation ForgotPassword($email: String!) {
  forgotPassword(input: {email: $email}) {
    clientMutationId
  }
}
    `;

export function useForgotPasswordMutation() {
  return Urql.useMutation<ForgotPasswordMutation, ForgotPasswordMutationVariables>(ForgotPasswordDocument);
};
export const InvitationDetailDocument = gql`
    query InvitationDetail($id: UUID!, $code: String) {
  ...SharedLayout_Query
  organizationForInvitation(invitationId: $id, code: $code) {
    id
    name
    slug
  }
}
    ${SharedLayout_QueryFragmentDoc}`;

export function useInvitationDetailQuery(options?: Omit<Urql.UseQueryArgs<never, InvitationDetailQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<InvitationDetailQuery, InvitationDetailQueryVariables | undefined>({ query: InvitationDetailDocument, variables: undefined, ...options });
};
export const InviteToOrganizationDocument = gql`
    mutation InviteToOrganization($organizationId: UUID!, $email: String, $username: String) {
  inviteToOrganization(
    input: {organizationId: $organizationId, email: $email, username: $username}
  ) {
    clientMutationId
  }
}
    `;

export function useInviteToOrganizationMutation() {
  return Urql.useMutation<InviteToOrganizationMutation, InviteToOrganizationMutationVariables>(InviteToOrganizationDocument);
};
export const LoginDocument = gql`
    mutation Login($username: String!, $password: String!) {
  login(input: {username: $username, password: $password}) {
    user {
      id
      username
      name
    }
  }
}
    `;

export function useLoginMutation() {
  return Urql.useMutation<LoginMutation, LoginMutationVariables>(LoginDocument);
};
export const LogoutDocument = gql`
    mutation Logout {
  logout {
    success
  }
}
    `;

export function useLogoutMutation() {
  return Urql.useMutation<LogoutMutation, LogoutMutationVariables>(LogoutDocument);
};
export const MakeEmailPrimaryDocument = gql`
    mutation MakeEmailPrimary($emailId: UUID!) {
  makeEmailPrimary(input: {emailId: $emailId}) {
    user {
      id
      userEmails(first: 50) {
        nodes {
          id
          isPrimary
        }
      }
    }
  }
}
    `;

export function useMakeEmailPrimaryMutation() {
  return Urql.useMutation<MakeEmailPrimaryMutation, MakeEmailPrimaryMutationVariables>(MakeEmailPrimaryDocument);
};
export const OrganizationBySlugDocument = gql`
    query OrganizationBySlug($slug: String!) {
  organizationBySlug(slug: $slug) {
    id
    name
    slug
  }
}
    `;

export function useOrganizationBySlugQuery(options?: Omit<Urql.UseQueryArgs<never, OrganizationBySlugQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<OrganizationBySlugQuery, OrganizationBySlugQueryVariables | undefined>({ query: OrganizationBySlugDocument, variables: undefined, ...options });
};
export const OrganizationMembersDocument = gql`
    query OrganizationMembers($slug: String!, $offset: Int = 0) {
  ...OrganizationPage_Query
  organizationBySlug(slug: $slug) {
    id
    ...OrganizationMembers_Organization
  }
}
    ${OrganizationPage_QueryFragmentDoc}
${OrganizationMembers_OrganizationFragmentDoc}`;

export function useOrganizationMembersQuery(options?: Omit<Urql.UseQueryArgs<never, OrganizationMembersQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<OrganizationMembersQuery, OrganizationMembersQueryVariables | undefined>({ query: OrganizationMembersDocument, variables: undefined, ...options });
};
export const OrganizationPageDocument = gql`
    query OrganizationPage($slug: String!) {
  ...OrganizationPage_Query
}
    ${OrganizationPage_QueryFragmentDoc}`;

export function useOrganizationPageQuery(options?: Omit<Urql.UseQueryArgs<never, OrganizationPageQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<OrganizationPageQuery, OrganizationPageQueryVariables | undefined>({ query: OrganizationPageDocument, variables: undefined, ...options });
};
export const RegisterDocument = gql`
    mutation Register($username: String!, $password: String!, $email: String!, $name: String) {
  register(
    input: {username: $username, password: $password, email: $email, name: $name}
  ) {
    user {
      id
      username
      name
    }
  }
}
    `;

export function useRegisterMutation() {
  return Urql.useMutation<RegisterMutation, RegisterMutationVariables>(RegisterDocument);
};
export const RemoveFromOrganizationDocument = gql`
    mutation RemoveFromOrganization($organizationId: UUID!, $userId: UUID!) {
  removeFromOrganization(
    input: {organizationId: $organizationId, userId: $userId}
  ) {
    clientMutationId
  }
}
    `;

export function useRemoveFromOrganizationMutation() {
  return Urql.useMutation<RemoveFromOrganizationMutation, RemoveFromOrganizationMutationVariables>(RemoveFromOrganizationDocument);
};
export const RequestAccountDeletionDocument = gql`
    mutation RequestAccountDeletion {
  requestAccountDeletion(input: {}) {
    success
  }
}
    `;

export function useRequestAccountDeletionMutation() {
  return Urql.useMutation<RequestAccountDeletionMutation, RequestAccountDeletionMutationVariables>(RequestAccountDeletionDocument);
};
export const ResendEmailVerificationDocument = gql`
    mutation ResendEmailVerification($emailId: UUID!) {
  resendEmailVerificationCode(input: {emailId: $emailId}) {
    success
  }
}
    `;

export function useResendEmailVerificationMutation() {
  return Urql.useMutation<ResendEmailVerificationMutation, ResendEmailVerificationMutationVariables>(ResendEmailVerificationDocument);
};
export const ResetPasswordDocument = gql`
    mutation ResetPassword($userId: UUID!, $token: String!, $password: String!) {
  resetPassword(
    input: {userId: $userId, resetToken: $token, newPassword: $password}
  ) {
    success
  }
}
    `;

export function useResetPasswordMutation() {
  return Urql.useMutation<ResetPasswordMutation, ResetPasswordMutationVariables>(ResetPasswordDocument);
};
export const SettingsEmailsDocument = gql`
    query SettingsEmails {
  ...SharedLayout_Query
  currentUser {
    id
    isVerified
    ...EmailsForm_User
  }
}
    ${SharedLayout_QueryFragmentDoc}
${EmailsForm_UserFragmentDoc}`;

export function useSettingsEmailsQuery(options?: Omit<Urql.UseQueryArgs<never, SettingsEmailsQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<SettingsEmailsQuery, SettingsEmailsQueryVariables | undefined>({ query: SettingsEmailsDocument, variables: undefined, ...options });
};
export const SettingsPasswordDocument = gql`
    query SettingsPassword {
  currentUser {
    id
    hasPassword
    userEmails(first: 1, condition: {isPrimary: true}) {
      nodes {
        id
        email
      }
    }
  }
}
    `;

export function useSettingsPasswordQuery(options?: Omit<Urql.UseQueryArgs<never, SettingsPasswordQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<SettingsPasswordQuery, SettingsPasswordQueryVariables | undefined>({ query: SettingsPasswordDocument, variables: undefined, ...options });
};
export const SettingsProfileDocument = gql`
    query SettingsProfile {
  ...SharedLayout_Query
  currentUser {
    id
    ...ProfileSettingsForm_User
  }
}
    ${SharedLayout_QueryFragmentDoc}
${ProfileSettingsForm_UserFragmentDoc}`;

export function useSettingsProfileQuery(options?: Omit<Urql.UseQueryArgs<never, SettingsProfileQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<SettingsProfileQuery, SettingsProfileQueryVariables | undefined>({ query: SettingsProfileDocument, variables: undefined, ...options });
};
export const SharedDocument = gql`
    query Shared {
  ...SharedLayout_Query
}
    ${SharedLayout_QueryFragmentDoc}`;

export function useSharedQuery(options?: Omit<Urql.UseQueryArgs<never, SharedQueryVariables | undefined>, 'query'>) {
  return Urql.useQuery<SharedQuery, SharedQueryVariables | undefined>({ query: SharedDocument, variables: undefined, ...options });
};
export const TransferOrganizationBillingContactDocument = gql`
    mutation TransferOrganizationBillingContact($organizationId: UUID!, $userId: UUID!) {
  transferOrganizationBillingContact(
    input: {organizationId: $organizationId, userId: $userId}
  ) {
    organization {
      id
      currentUserIsBillingContact
    }
  }
}
    `;

export function useTransferOrganizationBillingContactMutation() {
  return Urql.useMutation<TransferOrganizationBillingContactMutation, TransferOrganizationBillingContactMutationVariables>(TransferOrganizationBillingContactDocument);
};
export const TransferOrganizationOwnershipDocument = gql`
    mutation TransferOrganizationOwnership($organizationId: UUID!, $userId: UUID!) {
  transferOrganizationOwnership(
    input: {organizationId: $organizationId, userId: $userId}
  ) {
    organization {
      id
      currentUserIsOwner
    }
  }
}
    `;

export function useTransferOrganizationOwnershipMutation() {
  return Urql.useMutation<TransferOrganizationOwnershipMutation, TransferOrganizationOwnershipMutationVariables>(TransferOrganizationOwnershipDocument);
};
export const UnlinkUserAuthenticationDocument = gql`
    mutation UnlinkUserAuthentication($id: UUID!) {
  deleteUserAuthentication(input: {id: $id}) {
    user {
      id
      userAuthenticationsList(first: 50) {
        id
        identifier
        service
        createdAt
      }
    }
  }
}
    `;

export function useUnlinkUserAuthenticationMutation() {
  return Urql.useMutation<UnlinkUserAuthenticationMutation, UnlinkUserAuthenticationMutationVariables>(UnlinkUserAuthenticationDocument);
};
export const UpdateOrganizationDocument = gql`
    mutation UpdateOrganization($input: UpdateOrganizationInput!) {
  updateOrganization(input: $input) {
    organization {
      id
      slug
      name
    }
  }
}
    `;

export function useUpdateOrganizationMutation() {
  return Urql.useMutation<UpdateOrganizationMutation, UpdateOrganizationMutationVariables>(UpdateOrganizationDocument);
};
export const UpdateUserDocument = gql`
    mutation UpdateUser($id: UUID!, $patch: UserPatch!) {
  updateUser(input: {id: $id, patch: $patch}) {
    clientMutationId
    user {
      id
      name
      username
    }
  }
}
    `;

export function useUpdateUserMutation() {
  return Urql.useMutation<UpdateUserMutation, UpdateUserMutationVariables>(UpdateUserDocument);
};
export const VerifyEmailDocument = gql`
    mutation VerifyEmail($id: UUID!, $token: String!) {
  verifyEmail(input: {userEmailId: $id, token: $token}) {
    success
    query {
      currentUser {
        id
        isVerified
      }
    }
  }
}
    `;

export function useVerifyEmailMutation() {
  return Urql.useMutation<VerifyEmailMutation, VerifyEmailMutationVariables>(VerifyEmailDocument);
};